library(devtools)
source_url('http://cdn.rawgit.com/eric-czech/portfolio/master/functional/common/R/utils.R')
#source('~/repos/portfolio/functional/common/R/utils.R')
lib('logging')
basicConfig(loglevels['DEBUG'])
